export enum Parcel_Types {
  HOMEMADE_FOOD = 'HOME_FOOD',
  CLOTHES = 'CLOTHES',
  DOCUMENTS = 'DOCUMENTS',
  GIFTS = 'GIFTS',
  COSMETICS = 'COSMETICS',
  MEDICINE = 'MEDICINE',
  ACCESSORIES = 'ACCESSORIES',
  ELECTRONICS = 'ELECTRONICS',
}

export enum RIDES {
  BIKE = 'BIKE',
  CAR = 'CAR',
}
